version: 2
jobs:
  install:
    working_directory: ~/react-tide-boilerplate
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
      - restore_cache:
          key: v4-dependency-cache-{{ checksum "package.json" }}
      - run:
          command: |
            npm install
      - save_cache:
          key: v4-dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            - node_modules_prod.tar.gz

  test:
    working_directory: ~/react-tide-boilerplate
    docker:
      - image: circleci/node:8.9.0
    parallelism: 3
    steps:
      - checkout
      - restore_cache:
          key: v4-dependency-cache-{{ checksum "package.json" }}
      - run: npm run test

workflows:
  version: 2
  test:
    jobs:
      - install
      - test:
          requires:
            - install
